### ISSUE TITLE
installation error  (blendr3.3.2 steam)

### ISSUE THREAD

**Issue by mush555** [BlenderBoi/Frame_Ranger#1]
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger-master\__init__.py", line 14, in <module>
    from . import Modules
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger-master\Modules\__init__.py", line 3, in <module>
    from . import Action_Bin
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger-master\Modules\Action_Bin\__init__.py", line 3, in <module>
    from . import Panels
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger-master\Modules\Action_Bin\Panels.py", line 1, in <module>
    from . import Base_Panel
  File "C:\Users\myname\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger-master\Modules\Action_Bin\Base_Panel.py", line 3, in <module>
    from Frame_Ranger import Utility_Function
ModuleNotFoundError: No module named 'Frame_Ranger'

**Comment by bencresty** [comment]
Can confirm this. The same (No module named 'Frame_Ranger') happens on a normal Blender for Windows installation (Blender 3.4.1).

![image](https://user-images.githubusercontent.com/69322733/210167963-6f7ab548-62aa-4e64-953d-575c67162faf.png)

**Comment by BlenderBoi** [comment]
This is not plug and play yet, but to fix it, just rename the folder in the zip from Frame_Ranger-master to Frame_Ranger

The Proper fix will come soon

The One in Blendermarket and Gumroad are already renamed by default

**Comment by bencresty** [comment]
@BlenderBoi  Thanks! Renaming did the trick!

I understand you are busy and you'd like to have a proper fix (release it on github perhaps or make it foldername independent probably?), but I think for now a line about this in the README would be sufficient to help other people trying to install it for now.

Thanks for the quick response and for adding the addon to github! Keep up the great work!

**Comment by mush555** [comment]
@BlenderBoi 
By renaming it, I was able to confirm that it also works with the Steam version. Thank you for sharing a great addon.

**Comment by BlenderBoi** [comment]
problem solved, download addon from release section

**Comment by BlenderBoi** [comment]
Sorry I deleted the Wrong Message, Im kinda new to Github issue section

Anyway Problem Solved, Just Download Addon From Release Section From now on

**Comment by mush555** [comment]
thanks for the fix!
