### ISSUE TITLE
Issue using Object Action Manager with linked rig

### ISSUE THREAD

**Issue by josephsdaniels** [BlenderBoi/Frame_Ranger#4]
Fantastic addon, btw!
I am able to use the Object Action Manager effectively as long as I'm not working on linked assets. When working with a rig that is linked into the scene, I am not able to add or remove actions from the Action Bin. When I try, this is the error I get:

Python: Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger\Modules\Object_Action_Manager\LIST_Object_Action_Manager\Operators\Remove_Action_Slot.py", line 49, in invoke
    return self.execute(context)
  File "C:\Users\[username]\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger\Modules\Object_Action_Manager\LIST_Object_Action_Manager\Operators\Remove_Action_Slot.py", line 63, in execute
    action_list_helper.remove_slot(self.index, self.remove_action, cleanup=self.cleanup)
  File "C:\Users\[username]\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Frame_Ranger\Utility_Function\OAM_Functions.py", line 624, in remove_slot
    action_list.remove(index)
TypeError: bpy_prop_collection.remove() not supported for this collection

**Comment by BlenderBoi** [comment]
Hi, Unfortunately Frame Ranger Does not work with Linked Rig for now
